modLoader="javafml"
loaderVersion="[40,)"
license="Public Domain"

[[mods]]
modId="markscoins"
version="1.2.3"
displayName="Mark's Coins"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://pcmod.ddns.me"
logoFile="logo.png"
authors="markr, MCreator"
description='''
Add's an economy as well as special powers for some coins
'''

[[dependencies.markscoins]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




